### ISSUE TITLE
Incorrect plugin meta information

### ISSUE THREAD

**Issue by riartem** [lovata/oc-omnipay-shopaholic-plugin#1]
Hello. I reviewed your plugin and noticed that plugin has incorrect metadata in the plugin.yaml.

![image](https://user-images.githubusercontent.com/987517/34278994-4798261a-e6bf-11e7-9db2-c465de131da5.png)

![image](https://user-images.githubusercontent.com/987517/34279021-78840ec4-e6bf-11e7-9a1c-ebce6e588c7d.png)

**Comment by kharanenka** [comment]
Fixed in version 1.0.1
